### ISSUE TITLE
Need an event or some kind of way to know when a render update happens

### ISSUE THREAD

**Issue by isaacs** [vadimdemedes/ink-testing-library#22]
I have some dynamic things that change and do stuff over time, and I'm using ink to report it to the console.

It works great! The problem is, I'd like to test that when certain things happen, the render updates in specific ways.

What I'm doing now is just a lot of `await sleep(64)` all over the place, because it seems like the actual render is asynchronous or deferred or something. Reading the code, it seems like itl should be disabling the lodash throttle, because it sets `debug: true`, and indeed, if I hack ink to just make `const throttle = fn => fn`, I see the same behavior.

Everything seems to work fine when running one test at a time, but if I have a bunch of them running in several projects at once, taking up all the CPUs, things start to lag (especially in CI), and I get either multiple updates in a single frame, duplicate frames, or a frame doesn't update when I think it should have.  If I increase the timeouts, I usually get the results I expect, but that's a nondeterministic and slow workaround. (This is of course exactly what you want in the actual program, because it's better to drop frames than have choppy performance, and humans don't care if an intermediate state wasn't printed anyway.)

It'd be really nice if I could do something like:

```ts
const app = render(<SomeTagThatWatchesAnObject thing={whatever} />)
app.on('render', (frame) => {
  verifyItIsWhatIsExpected(frame)
})
triggerEventsAndStuffOnObject(whatever)
```

Or, perhaps I'm just going about this wrong? Is there a better way than looking at `app.frames`? Or some kind of a `flush()` method that could render on demand and push out all pending state changes?

**Comment by vadimdemedes** [comment]
Would you be using that feature in test environment only or does this power some features in your CLI? Could you share a small reproducible example (Ink component + test) that shows the exact desired behavior? This would help me understand the use case better and find the right solution.

**Comment by isaacs** [comment]
I'd only be using this in my tests.

Basically, I have some Test objects that do various things, and when they do, hooks trigger app updates.  But I have to add sleeps in places to actually get the frames I expect, and even then, it's kind of flaky. For example, [this test](https://github.com/tapjs/tapjs/blob/main/src/reporter/test/hooks/use-assert-totals.tsx) fails if the sleeps are removed. But it sometimes _also_ fails if the CPU is just busy. Really, I would prefer to just have something I could `await` that will tell me that it's done all the updating it needs to do, and it's safe to look at the frames.

**Comment by isaacs** [comment]
Aha!  I figured out the issue. It's not Ink, it's just an edge case of React that I'd never encountered before. Updating here for posterity.

I still think a "update happened" or "work is scheduled, but not yet completed" would be handy for some use cases in Ink, but in my case, I think I might not need it.

The issue is that I had a hook and tag something like this (simplified example)

```tsx
// returns an array of all the data emitted on the specified event
const useEvent = (emitter: EventEmitter, event: string): any[][] => {
  const [data, updateData] = useState<any[][]>([])
  useEffect(() => {
    const handler = (...args: any[]) => updateData([...data, args])
    emitter.on(event, handler)
    return () => emitter.off(event, handler)
  }, [data, emitter])
}

// shows the things that were emitted
const Events: FC<{ emitter: EventEmitter, event: string }> = ({ emitter, event }) => {
  const data = useEvent(emitter, event)
  return (
    <Box flexDirection="column">
      {data.map((args: any[]) => (
        <Text>{args.join(', ')}</Text>
      ))}
    </Box>
  )
}

const emitter = new EventEmitter()
const app = render(<Events emitter={emitter} event="blah" />)
emitter.emit("blah", "bloo")
// expect: ['blah'], actual ['']
console.log(app.frames)
```

The answer is to use `useLayoutEffect` instead, because `useEffect` is deferred if called during a render.

In a web browser context, this makes a lot more sense, because locking up the browser is a pretty terrible thing to do even for a few dozen ms, and `useLayoutEffect` is almost always a bad idea.

But a node process really _can't_ lock up the terminal in any meaningful way, and when dealing with synchronous events in Ink, it's crucial to run hooks right away.

Probably would be a good idea to have a note about this in the Ink docs. Happy to send a PR if you agree, but if anyone else wants to, that's fine too. If not, or until then, hopefully this issue is helpful to someone else pulling their hair in the future.
