### ISSUE TITLE
stdin.write doesn't work

### ISSUE THREAD

**Issue by luixo** [vadimdemedes/ink-testing-library#25]
Hello, `stdin.write` doesn't work with the latest ink version.
The fix is already [commited](https://github.com/vadimdemedes/ink-testing-library/commit/f44b077e9a05a1d615bab41c72906726d34ea085), but was never released on npm.
Can this be fixed?

**Comment by Opeyem1a** [comment]
Having the same issue, has anyone had any success with this?

**Comment by sindresorhus** [comment]
https://github.com/vadimdemedes/ink-testing-library/releases/tag/v4.0.0
