### ISSUE TITLE
Cannot find module 'ink-testing-library' or its corresponding type declarations

### ISSUE THREAD

**Issue by nukeop** [vadimdemedes/ink-testing-library#26]
I'm getting this message in a blank project even after installing just this single library. As far as I can see the library's files and declarations are present in node_modules. Inlining what's under the `exports` key in `package.json` makes it work, so I was able to use `patch-package` to fix it for myself.

Node 20.15.0, npm 10.8.0

**Comment by sindresorhus** [comment]
This is usually a sign that your project is not fully ESM, which is required by this package. https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by nukeop** [comment]
Well, I'm drawing a line if a package I import wants me to go out of my way and adapt my entire project to it. Shouldn't this stuff be in the readme?

And if I can make it work with a 2-line change, why not simply change it upstream?
