### ISSUE TITLE
How to set up with Jest?

### ISSUE THREAD

**Issue by hagnerd** [vadimdemedes/ink-testing-library#8]
Not sure where I'm going wrong but I can't seem to get Ink/Ink testing library to play nicely with Jest. I'm sure I'm doing something extremely silly, but it would be great to see an example of how to do this? 

I'm getting this error
![Screen Shot 2019-07-08 at 10 41 06 AM](https://user-images.githubusercontent.com/6313764/60833472-ea960a00-a183-11e9-969f-1747d7bef6d2.png)

I've tried what I understand to be the normal ways to get React, Jest and Babel to play nicely. I'm working on setting up a minimal reproduction.

**Comment by vadimdemedes** [comment]
You need to set up Jest for testing React apps, see https://jestjs.io/docs/en/tutorial-react.
